<<<<<<< HEAD

=======
>>>>>>> d965691a6cd49fdf63aac1370eaca21353778a7a
sqlite: &sqlite
    adapter: sqlite3
    database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
    adapter: postgresql
    username: postgres
    password:
    database: webcalendar_<%= Rails.env %>
    min_messages: ERROR


defaults: &defaults
    pool: 16
    timeout: 5000
    host: localhost
    <<: *<%= p ENV['DB'] || "sqlite" %>

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults
