sqlite: &sqlite
    adapter: sqlite3
    database: db/<%= Rails.env %>.sqlite3

defaults: &defaults
    pool: 16
    timeout: 5000
    host: localhost
    <<: *<%= p ENV['DB'] || "sqlite" %>

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults